# Generated by Django 2.1.4 on 2019-01-20 01:09

from django.db import migrations

def copy_src_to_dst(source, destination):
    """
    1# Para cada ABC(Source), instaciar um MTI (Destination) com todos os atributos
    2# Salvar MTI
    3# Associar os speakers to ABC no MTI
    4# Deletar o ABC
    """
    for src in source.objects.all():
        dts = destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dts.save()
        dts.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
